---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
        - name: log
          persistentVolumeClaim:
            claimName: myapp
      containers:
        - name: myapp
          image: islishude/k8s-example-server
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 10200
          volumeMounts:
            - mountPath: /log
              name: log

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
    - port: 10200
      targetPort: 10200
      nodePort: 31020
