---
apiVersion: v1
kind: Namespace
metadata:
  name: islishude

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: islishude
spec:
  selector:
    matchLabels:
      app: echoserver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - name: echoserver
          image: islishude/echo:v2
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "256m"
          readinessProbe:
            tcpSocket:
              port: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: "/ping"

---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: islishude
spec:
  selector:
    app: echoserver
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31020
